import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // useEffect(() => {
  //   var ads = document.getElementsByClassName("adsbygoogle").length;
  //   for (var i = 0; i < ads; i++) {
  //     try {
  //       (window.adsbygoogle = window.adsbygoogle || []).push({});
  //     } catch (e) {}
  //   }
  // }, []);
  return (
    <html lang="en">
      <head>
        {/* <meta name="google-adsense-account" content="ca-pub-4293091400623161" /> */}
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4293091400623161"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        ></Script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
